#!/usr/bin/env node
// ============================================================
// DEPLOY.JS
// Build + deploy a company website to Vercel
//
// Usage:
//   node deploy.js "alb-shining"          → deploy one company by slug
//   node deploy.js --all                  → deploy all completed configs
//   node deploy.js --list                 → show deploy status
//
// Requires: npx vercel login (run once before deploying)
// ============================================================

import fs from 'fs';
import path from 'path';
import { execSync, spawnSync } from 'child_process';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const CONFIGS_DIR = path.join(__dirname, 'src', 'configs');
const INDEX_FILE = path.join(CONFIGS_DIR, 'index.ts');
const PROGRESS_FILE = path.join(__dirname, 'progress.json');
const DEPLOY_LOG = path.join(__dirname, 'deploy-log.json');

// ============================================================
// PROGRESS
// ============================================================
function loadProgress() {
    if (!fs.existsSync(PROGRESS_FILE)) return { completed: [], failed: [] };
    return JSON.parse(fs.readFileSync(PROGRESS_FILE, 'utf8'));
}

function loadDeployLog() {
    if (!fs.existsSync(DEPLOY_LOG)) return {};
    return JSON.parse(fs.readFileSync(DEPLOY_LOG, 'utf8'));
}

function saveDeployLog(log) {
    fs.writeFileSync(DEPLOY_LOG, JSON.stringify(log, null, 2), 'utf8');
}

// ============================================================
// CONFIG SWITCHING
// ============================================================
function switchConfig(slug) {
    const configFile = path.join(CONFIGS_DIR, `${slug}.ts`);
    if (!fs.existsSync(configFile)) {
        throw new Error(`Config not found: src/configs/${slug}.ts`);
    }
    const content = `// Auto-generated by deploy.js\nimport activeConfig from './${slug}';\nexport default activeConfig;\n`;
    fs.writeFileSync(INDEX_FILE, content, 'utf8');
}

// ============================================================
// BUILD
// ============================================================
function build(slug) {
    console.log(`  🔨 Building ${slug}...`);
    execSync('npm run build', { stdio: 'inherit', cwd: __dirname });
    console.log(`  ✅ Build complete`);
}

// ============================================================
// DEPLOY TO VERCEL
// ============================================================
function deployToVercel(slug) {
    const projectName = `cleaning-${slug}`;
    console.log(`  🚀 Deploying to Vercel as "${projectName}"...`);

    // Remove any existing .vercel link so each company gets its own project
    const vercelDir = path.join(__dirname, 'dist', '.vercel');
    if (fs.existsSync(vercelDir)) fs.rmSync(vercelDir, { recursive: true });

    try {
        const output = execSync(
            `npx vercel deploy dist --prod --yes --name ${projectName}`,
            { cwd: __dirname, encoding: 'utf8', timeout: 180000, stdio: ['pipe', 'pipe', 'pipe'] }
        );

        // Prefer the clean alias URL (no hash), fallback to any vercel.app URL
        const aliasMatch = output.match(/Aliased:\s+(https:\/\/[^\s]+)/i);
        const anyMatch = output.match(/https:\/\/cleaning-[a-z0-9-]+\.vercel\.app/i);
        const url = aliasMatch ? aliasMatch[1] : anyMatch ? anyMatch[0] : null;

        if (!url) {
            console.log(`  ⚠  No URL found in output:\n${output.slice(0, 400)}`);
            return null;
        }

        return url;
    } catch (e) {
        // execSync throws on non-zero exit, but output may still have the URL
        const out = (e.stdout || '') + (e.stderr || '');
        const aliasMatch = out.match(/Aliased:\s+(https:\/\/[^\s]+)/i);
        const anyMatch = out.match(/https:\/\/cleaning-[a-z0-9-]+\.vercel\.app/i);
        const url = aliasMatch ? aliasMatch[1] : anyMatch ? anyMatch[0] : null;
        if (url) return url;
        console.log(`  ❌ Deploy error: ${e.message}`);
        return null;
    }
}

// ============================================================
// DEPLOY ONE COMPANY
// ============================================================
async function deployCompany(slug, force = false) {
    const log = loadDeployLog();

    if (!force && log[slug] && log[slug].url) {
        console.log(`  ⏭  SKIP: ${slug} already deployed → ${log[slug].url}`);
        return log[slug].url;
    }

    console.log(`\n━━━ Deploying: ${slug} ━━━`);

    try {
        switchConfig(slug);
        build(slug);
        const url = deployToVercel(slug);

        if (url) {
            log[slug] = { url, deployedAt: new Date().toISOString() };
            saveDeployLog(log);
            console.log(`  ✅ Live at: ${url}`);
            return url;
        } else {
            console.log(`  ❌ Deploy failed for ${slug}`);
            return null;
        }
    } catch (e) {
        console.log(`  ❌ Error: ${e.message}`);
        return null;
    }
}

// ============================================================
// MAIN
// ============================================================
async function main() {
    const args = process.argv.slice(2);

    if (args.length === 0 || args[0] === '--help') {
        console.log('\n🚀  Deploy — Build + publish company sites to Vercel');
        console.log('━'.repeat(50));
        console.log('\nFirst time setup: run  npx vercel login');
        console.log('\nUsage:');
        console.log('  node deploy.js alb-shining          Deploy one company');
        console.log('  node deploy.js --all                 Deploy all completed configs');
        console.log('  node deploy.js --list                Show all deploy URLs\n');
        return;
    }

    // --list
    if (args[0] === '--list') {
        const log = loadDeployLog();
        const entries = Object.entries(log);
        if (entries.length === 0) {
            console.log('\n  No deployments yet. Run: node deploy.js --all\n');
            return;
        }
        console.log('\n🌐  Deployed sites:\n');
        entries.forEach(([slug, data]) => {
            console.log(`  ✅  ${slug.padEnd(30)} ${data.url}`);
        });
        console.log('');
        return;
    }

    // --all
    if (args[0] === '--all') {
        const progress = loadProgress();
        const slugs = progress.completed;
        console.log(`\n🚀  Deploying ${slugs.length} completed configs...\n`);
        const urls = {};
        for (const slug of slugs) {
            const url = await deployCompany(slug);
            if (url) urls[slug] = url;
        }
        console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
        console.log('🌐  Live URLs:');
        Object.entries(urls).forEach(([slug, url]) => console.log(`  ${slug.padEnd(30)} ${url}`));
        console.log('');
        return;
    }

    // single slug
    const slug = args[0].replace(/\s+/g, '-').toLowerCase();
    const force = args.includes('--force');
    await deployCompany(slug, force);
    console.log('');
}

main().catch(err => {
    console.error('\n❌  Fatal:', err.message);
    process.exit(1);
});
