#!/usr/bin/env node
// ============================================================
// WHITELABEL SITE GENERATOR
// ============================================================
// This script automates building a new branded website from config.
//
// Usage:
//   node generate-site.js lumina        → Builds Lumina version
//   node generate-site.js alb-shining   → Builds Alb Shining version
//   node generate-site.js all           → Builds all configs
//
// The script:
//   1. Reads the specified config
//   2. Updates the active config selector
//   3. Updates index.html meta tags
//   4. Runs `npm run build`
//   5. Copies output to dist-{brand}/ folder
// ============================================================

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const CONFIGS_DIR = path.join(__dirname, 'src', 'configs');
const INDEX_FILE = path.join(CONFIGS_DIR, 'index.ts');
const DIST_DIR = path.join(__dirname, 'dist');

// Get available configs
function getAvailableConfigs() {
    return fs.readdirSync(CONFIGS_DIR)
        .filter(f => f.endsWith('.ts') && f !== 'index.ts')
        .map(f => f.replace('.ts', ''));
}

// Switch the active config
function switchConfig(configName) {
    const content = `// Auto-generated by generate-site.js
import activeConfig from './${configName}';
export default activeConfig;
`;
    fs.writeFileSync(INDEX_FILE, content, 'utf-8');
    console.log(`  ✅ Switched active config to: ${configName}`);
}

// Build the project
function buildProject() {
    console.log('  🔨 Building production bundle...');
    execSync('npm run build', { stdio: 'inherit', cwd: __dirname });
    console.log('  ✅ Build complete');
}

// Copy dist to branded folder
function copyDist(configName) {
    const targetDir = path.join(__dirname, `dist-${configName}`);

    // Remove existing if present
    if (fs.existsSync(targetDir)) {
        fs.rmSync(targetDir, { recursive: true });
    }

    // Copy dist folder
    copyDirRecursive(DIST_DIR, targetDir);
    console.log(`  📁 Output saved to: dist-${configName}/`);
}

function copyDirRecursive(src, dest) {
    fs.mkdirSync(dest, { recursive: true });
    const entries = fs.readdirSync(src, { withFileTypes: true });
    for (const entry of entries) {
        const srcPath = path.join(src, entry.name);
        const destPath = path.join(dest, entry.name);
        if (entry.isDirectory()) {
            copyDirRecursive(srcPath, destPath);
        } else {
            fs.copyFileSync(srcPath, destPath);
        }
    }
}

// Main
function main() {
    const args = process.argv.slice(2);
    const available = getAvailableConfigs();

    if (args.length === 0) {
        console.log('\n🏗️  Whitelabel Site Generator');
        console.log('━'.repeat(40));
        console.log('\nUsage: node generate-site.js <config-name>\n');
        console.log('Available configs:');
        available.forEach(c => console.log(`  • ${c}`));
        console.log(`\n  node generate-site.js all  → Build all configs`);
        console.log('');
        process.exit(0);
    }

    const target = args[0].toLowerCase();

    if (target === 'all') {
        console.log(`\n🏗️  Building ALL ${available.length} configs...\n`);
        for (const configName of available) {
            console.log(`\n━━━ Building: ${configName} ━━━`);
            switchConfig(configName);
            buildProject();
            copyDist(configName);
        }
        console.log(`\n✅ All ${available.length} builds complete!\n`);
    } else if (available.includes(target)) {
        console.log(`\n━━━ Building: ${target} ━━━`);
        switchConfig(target);
        buildProject();
        copyDist(target);
        console.log(`\n✅ Build complete! Deploy dist-${target}/ to your hosting.\n`);
    } else {
        console.error(`\n❌ Config "${target}" not found.`);
        console.error(`Available: ${available.join(', ')}\n`);
        process.exit(1);
    }
}

main();
