import type { CompanyConfig } from '../company_config';

// ============================================================
// SHELTERTECH UK LTD
// ============================================================
// AUTO-GENERATED by scrape-config.js — 2026-02-27
// Source: CSV lead data + website scrape (http://www.sheltertech.co.uk/)
// Google: 4.6★ | 10 reviews
//
// Search "TODO" to find the 8 fields that need manual review.
// Everything else is auto-filled from real data.
// ============================================================

const config: CompanyConfig = {
    // --- IDENTITY ---
    identity: {
        companyName: "SHELTERTECH UK",
        companyNameFull: "Sheltertech UK Ltd",
        logoInitial: "S",
        logoUrl: "https://lirp.cdn-website.com/3ee0af83/dms3rep/multi/opt/STUK-LOGO-2000px-456w.png", // scraped — verify it loads correctly
        tagline: "Professional Cleaning\nServices in Uxbridge", // TODO: write a compelling tagline
        subTagline: "Trusted, professional cleaning services for businesses and homes across Uxbridge. We deliver spotless results every time.", // TODO: personalize from their website
        badgeText: "PROFESSIONAL CLEANING SERVICES",
        metaTitle: "Sheltertech UK Ltd | Professional Cleaning Services Uxbridge",
        metaDescription: "Call Shelter Tech UK Ltd for the best and affordable Legionella Risk Assessments as well as closed loop water treatment in Windsor, Epsom and London.",
    },

    // --- STYLING (auto-extracted from website) ---
    styling: {
        primaryColor: "#68CCD1", // scraped from website
        accentColor: "#f59e0b", // TODO: check website for accent color
        surfaceColor: "#f8fafc",
        fontSans: '"Inter", ui-sans-serif, system-ui, sans-serif',
        fontSerif: '"Playfair Display", ui-serif, Georgia, serif',
        fontDisplay: '"Inter", ui-sans-serif, system-ui, sans-serif',
        googleFontsImport: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&family=Playfair+Display:ital,wght@0,700;1,700&display=swap",
    },

    // --- CONTACT (auto-filled from CSV — verified data) ---
    contact: {
        phone: "+44 1895 602977",
        phoneTel: "+441895602977",
        email: "info@sheltertech.co.uk",
        address: "Suite A, Island Site, Eskdale Rd, Uxbridge UB8 2RT",
        addressLine2: "Uxbridge",
        socialMedia: {
            facebook: "https://www.facebook.com/Sheltertech.co.uk",
        },
    },

    // --- HERO ---
    hero: {
        backgroundImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=2070&auto=format&fit=crop", // TODO: pick the best hero image for this company type
        backgroundAlt: "Professional cleaning team at work in Uxbridge",
        ctaPrimary: "Get a Free Quote",
        ctaSecondary: "Call Us Now",
    },

    // --- SERVICES ---
    // TODO: replace with their real services from http://www.sheltertech.co.uk/
    services: {
        sectionTitle: "Our Services",
        sectionSubtitle: "Professional cleaning solutions tailored to your specific needs across Uxbridge.",
        items: [
            {
                title: "Commercial Cleaning", // TODO: use their actual service names
                description: "Professional commercial cleaning for offices, shops, and business premises in Uxbridge. Reliable, vetted staff delivering consistent results.",
                image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2301&auto=format&fit=crop",
                alt: "Clean professional office environment",
            },
            {
                title: "Deep Cleaning",
                description: "Intensive deep clean services for premises that need a thorough refresh. Industrial-grade equipment and eco-friendly products used throughout.",
                image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=2070&auto=format&fit=crop",
                alt: "Professional deep cleaning in progress",
            },
            {
                title: "Regular Maintenance",
                description: "Scheduled maintenance cleaning to keep your premises spotless day after day. Flexible scheduling to minimise disruption to your business.",
                image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
                alt: "Regular maintenance cleaning service",
            },
        ],
    },

    // --- PRICING ---
    // TODO: find their actual rates at http://www.sheltertech.co.uk/ and replace these placeholders
    pricing: {
        sectionTitle: "Pricing",
        sectionSubtitle: "Competitive rates with no hidden fees. Contact us for a free, tailored quote.",
        plans: [
            {
                name: "Regular Contract",
                description: "Scheduled ongoing cleaning",
                features: [
                    "Flexible daily or weekly schedule",
                    "Dedicated cleaning team",
                    "All equipment included",
                    "Fully insured staff",
                ],
            },
            {
                name: "Bespoke Package",
                description: "Tailored to your requirements",
                features: [
                    "Custom cleaning plan",
                    "Free site assessment",
                    "Vetted & DBS-checked staff",
                    "Quality guarantee",
                ],
                highlight: true,
            },
            {
                name: "One-Off Deep Clean",
                description: "Intensive single session",
                features: [
                    "Full premises deep clean",
                    "Industrial-grade equipment",
                    "Eco-friendly products",
                    "Weekend availability",
                ],
            },
        ],
    },

    // --- REVIEWS ---
    // Google: 4.6★ average from 10 reviews
    reviews: {
        averageRating: "4.6/5",
        items: [
            { // TODO: replace with real review text from Google Maps
                name: "Google Reviewer",
                role: "Verified Google Review",
                text: "Excellent service — very professional and reliable. Would highly recommend to anyone needing quality cleaning services in Uxbridge.",
                rating: 5,
            },
            { // TODO: replace with real review text from Google Maps
                name: "Google Reviewer",
                role: "Verified Google Review",
                text: "Very impressed with the standard of work. The team was punctual, thorough and friendly. Will definitely be using again.",
                rating: 5,
            },
            { // TODO: replace with real review text from Google Maps
                name: "Google Reviewer",
                role: "Verified Google Review",
                text: "Reliable, professional service. Our premises have never looked better. Great value for money.",
                rating: 5,
            },
        ],
    },

    // --- SERVICE AREAS ---
    // TODO: replace with their actual coverage areas from http://www.sheltertech.co.uk/
    areas: {
        sectionTitle: "Areas We Cover",
        sectionSubtitle: "Providing professional cleaning services across Uxbridge and the surrounding areas.",
        locations: [
            "Uxbridge",
            "Uxbridge",
            "Hillingdon",
            "Hayes",
            "West Drayton",
            "Ickenham",
            "Harefield",
        ],
    },

    // --- FOOTER ---
    footer: {
        description: "Sheltertech UK Ltd — professional cleaning services you can trust. Fully insured, vetted staff, and a commitment to quality on every visit.", // TODO: personalize
        copyright: "© 2026 Sheltertech UK Ltd | All Rights Reserved.",
    },

    // --- TRUST BADGES ---
    trustBadges: ["Fully Insured", "Vetted Staff", "4.6★ Rated", "Free Quote"], // TODO: use their actual trust badges/USPs
};

export default config;
