import type { CompanyConfig } from '../company_config';

// ============================================================
// SMOOTH CLEAN - HOME CLEANERS LONDON
// ============================================================
// AUTO-GENERATED by scrape-config.js — 2026-02-27
// Source: CSV lead data + website scrape (https://smoothclean.co.uk/)
// Google: 5.0★ | 3 reviews
//
// Search "TODO" to find the 12 fields that need manual review.
// Everything else is auto-filled from real data.
// ============================================================

const config: CompanyConfig = {
    // --- IDENTITY ---
    identity: {
        companyName: "SMOOTH CLEAN - HOME CLEANERS LONDON",
        companyNameFull: "Smooth Clean - Home Cleaners London",
        logoInitial: "S",
        // logoUrl: "", // TODO: add logo URL if available
        tagline: "Professional Cleaning\nServices in London", // TODO: write a compelling tagline
        subTagline: "Trusted, professional cleaning services for businesses and homes across London. We deliver spotless results every time.", // TODO: personalize from their website
        badgeText: "PROFESSIONAL CLEANING SERVICES",
        metaTitle: "Smooth Clean - Home Cleaners London | Professional Cleaning Services London",
        metaDescription: "Smooth Clean - Home Cleaners London — Professional cleaning services in London. Get a free quote today.",
    },

    // --- STYLING (auto-extracted from website) ---
    styling: {
        primaryColor: "#1a3a5c", // TODO: check website for brand color
        accentColor: "#f59e0b", // TODO: check website for accent color
        surfaceColor: "#f8fafc",
        fontSans: '"Inter", ui-sans-serif, system-ui, sans-serif',
        fontSerif: '"Playfair Display", ui-serif, Georgia, serif',
        fontDisplay: '"Inter", ui-sans-serif, system-ui, sans-serif',
        googleFontsImport: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&family=Playfair+Display:ital,wght@0,700;1,700&display=swap",
    },

    // --- CONTACT (auto-filled from CSV — verified data) ---
    contact: {
        phone: "+44 7512 341346",
        phoneTel: "+447512341346",
        email: "info@smoothclean.co.uk",
        address: "London",
        addressLine2: "London",
        socialMedia: {
            // TODO: add social media links
        },
    },

    // --- HERO ---
    hero: {
        backgroundImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=2070&auto=format&fit=crop", // TODO: pick the best hero image for this company type
        backgroundAlt: "Professional cleaning team at work in London",
        ctaPrimary: "Get a Free Quote",
        ctaSecondary: "Call Us Now",
    },

    // --- SERVICES ---
    // TODO: replace with their real services from https://smoothclean.co.uk/
    services: {
        sectionTitle: "Our Services",
        sectionSubtitle: "Professional cleaning solutions tailored to your specific needs across London.",
        items: [
            {
                title: "Commercial Cleaning", // TODO: use their actual service names
                description: "Professional commercial cleaning for offices, shops, and business premises in London. Reliable, vetted staff delivering consistent results.",
                image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2301&auto=format&fit=crop",
                alt: "Clean professional office environment",
            },
            {
                title: "Deep Cleaning",
                description: "Intensive deep clean services for premises that need a thorough refresh. Industrial-grade equipment and eco-friendly products used throughout.",
                image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=2070&auto=format&fit=crop",
                alt: "Professional deep cleaning in progress",
            },
            {
                title: "Regular Maintenance",
                description: "Scheduled maintenance cleaning to keep your premises spotless day after day. Flexible scheduling to minimise disruption to your business.",
                image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
                alt: "Regular maintenance cleaning service",
            },
        ],
    },

    // --- PRICING ---
    // TODO: find their actual rates at https://smoothclean.co.uk/ and replace these placeholders
    pricing: {
        sectionTitle: "Pricing",
        sectionSubtitle: "Competitive rates with no hidden fees. Contact us for a free, tailored quote.",
        plans: [
            {
                name: "Regular Contract",
                description: "Scheduled ongoing cleaning",
                features: [
                    "Flexible daily or weekly schedule",
                    "Dedicated cleaning team",
                    "All equipment included",
                    "Fully insured staff",
                ],
            },
            {
                name: "Bespoke Package",
                description: "Tailored to your requirements",
                features: [
                    "Custom cleaning plan",
                    "Free site assessment",
                    "Vetted & DBS-checked staff",
                    "Quality guarantee",
                ],
                highlight: true,
            },
            {
                name: "One-Off Deep Clean",
                description: "Intensive single session",
                features: [
                    "Full premises deep clean",
                    "Industrial-grade equipment",
                    "Eco-friendly products",
                    "Weekend availability",
                ],
            },
        ],
    },

    // --- REVIEWS ---
    // Google: 5.0★ average from 3 reviews
    reviews: {
        averageRating: "5.0/5",
        items: [
            { // TODO: replace with real review text from Google Maps
                name: "Google Reviewer",
                role: "Verified Google Review",
                text: "Excellent service — very professional and reliable. Would highly recommend to anyone needing quality cleaning services in London.",
                rating: 5,
            },
            { // TODO: replace with real review text from Google Maps
                name: "Google Reviewer",
                role: "Verified Google Review",
                text: "Very impressed with the standard of work. The team was punctual, thorough and friendly. Will definitely be using again.",
                rating: 5,
            },
            { // TODO: replace with real review text from Google Maps
                name: "Google Reviewer",
                role: "Verified Google Review",
                text: "Reliable, professional service. Our premises have never looked better. Great value for money.",
                rating: 5,
            },
        ],
    },

    // --- SERVICE AREAS ---
    // TODO: replace with their actual coverage areas from https://smoothclean.co.uk/
    areas: {
        sectionTitle: "Areas We Cover",
        sectionSubtitle: "Providing professional cleaning services across London and the surrounding areas.",
        locations: [
            "London",
            "Uxbridge",
            "Hillingdon",
            "Hayes",
            "West Drayton",
            "Ickenham",
            "Harefield",
        ],
    },

    // --- FOOTER ---
    footer: {
        description: "Smooth Clean - Home Cleaners London — professional cleaning services you can trust. Fully insured, vetted staff, and a commitment to quality on every visit.", // TODO: personalize
        copyright: "© 2026 Smooth Clean - Home Cleaners London | All Rights Reserved.",
    },

    // --- TRUST BADGES ---
    trustBadges: ["Fully Insured", "Vetted Staff", "5.0★ Rated", "Free Quote"], // TODO: use their actual trust badges/USPs
};

export default config;
