import type { CompanyConfig } from '../company_config';

// ============================================================
// SUPREME FACILITIES LTD
// ============================================================
// AUTO-GENERATED by scrape-config.js — 2026-02-27
// Source: CSV lead data + website scrape (https://supremefacilities.co.uk/)
// Google: 4.4★ | 20 reviews
//
// Search "TODO" to find the 8 fields that need manual review.
// Everything else is auto-filled from real data.
// ============================================================

const config: CompanyConfig = {
    // --- IDENTITY ---
    identity: {
        companyName: "SUPREME FACILITIES",
        companyNameFull: "Supreme Facilities Ltd",
        logoInitial: "S",
        logoUrl: "https://supremefacilities.co.uk/wp-content/uploads/2024/04/logo-sp.png", // scraped — verify it loads correctly
        tagline: "Professional Cleaning\nServices in Uxbridge", // TODO: write a compelling tagline
        subTagline: "Trusted, professional cleaning services for businesses and homes across Uxbridge. We deliver spotless results every time.", // TODO: personalize from their website
        badgeText: "PROFESSIONAL CLEANING SERVICES",
        metaTitle: "Supreme Facilities Ltd | Professional Cleaning Services Uxbridge",
        metaDescription: "Supreme Facilities Ltd — Professional cleaning services in Uxbridge. Get a free quote today.",
    },

    // --- STYLING (auto-extracted from website) ---
    styling: {
        primaryColor: "#1CCEBC", // scraped from website
        accentColor: "#5EF3ED", // scraped from website
        surfaceColor: "#f8fafc",
        fontSans: '"Inter", ui-sans-serif, system-ui, sans-serif',
        fontSerif: '"Playfair Display", ui-serif, Georgia, serif',
        fontDisplay: '"Inter", ui-sans-serif, system-ui, sans-serif',
        googleFontsImport: "https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&#038;family=Nunito+Sans:opsz,wght@6..12,200;6..12,300;6..12,400;6..12,500;6..12,600;6..12,700;6..12,800;6..12,900;6..12,1000&#038;display=swap%20rel=stylesheet%20rel=stylesheet",
    },

    // --- CONTACT (auto-filled from CSV — verified data) ---
    contact: {
        phone: "+44 20 4532 0300",
        phoneTel: "+442045320300",
        email: "info@supremefacilities.co.uk",
        address: "Beasley Court Warwick Place, Uxbridge UB8 1PE",
        addressLine2: "Uxbridge",
        socialMedia: {
            facebook: "https://www.facebook.com/supremefacilities.co",
            instagram: "https://www.instagram.com/supremefacilitiesuk",
        },
    },

    // --- HERO ---
    hero: {
        backgroundImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=2070&auto=format&fit=crop", // TODO: pick the best hero image for this company type
        backgroundAlt: "Professional cleaning team at work in Uxbridge",
        ctaPrimary: "Get a Free Quote",
        ctaSecondary: "Call Us Now",
    },

    // --- SERVICES ---
    // TODO: replace with their real services from https://supremefacilities.co.uk/
    services: {
        sectionTitle: "Our Services",
        sectionSubtitle: "Professional cleaning solutions tailored to your specific needs across Uxbridge.",
        items: [
            {
                title: "Commercial Cleaning", // TODO: use their actual service names
                description: "Professional commercial cleaning for offices, shops, and business premises in Uxbridge. Reliable, vetted staff delivering consistent results.",
                image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2301&auto=format&fit=crop",
                alt: "Clean professional office environment",
            },
            {
                title: "Deep Cleaning",
                description: "Intensive deep clean services for premises that need a thorough refresh. Industrial-grade equipment and eco-friendly products used throughout.",
                image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=2070&auto=format&fit=crop",
                alt: "Professional deep cleaning in progress",
            },
            {
                title: "Regular Maintenance",
                description: "Scheduled maintenance cleaning to keep your premises spotless day after day. Flexible scheduling to minimise disruption to your business.",
                image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
                alt: "Regular maintenance cleaning service",
            },
        ],
    },

    // --- PRICING ---
    // TODO: find their actual rates at https://supremefacilities.co.uk/ and replace these placeholders
    pricing: {
        sectionTitle: "Pricing",
        sectionSubtitle: "Competitive rates with no hidden fees. Contact us for a free, tailored quote.",
        plans: [
            {
                name: "Regular Contract",
                description: "Scheduled ongoing cleaning",
                features: [
                    "Flexible daily or weekly schedule",
                    "Dedicated cleaning team",
                    "All equipment included",
                    "Fully insured staff",
                ],
            },
            {
                name: "Bespoke Package",
                description: "Tailored to your requirements",
                features: [
                    "Custom cleaning plan",
                    "Free site assessment",
                    "Vetted & DBS-checked staff",
                    "Quality guarantee",
                ],
                highlight: true,
            },
            {
                name: "One-Off Deep Clean",
                description: "Intensive single session",
                features: [
                    "Full premises deep clean",
                    "Industrial-grade equipment",
                    "Eco-friendly products",
                    "Weekend availability",
                ],
            },
        ],
    },

    // --- REVIEWS ---
    // Google: 4.4★ average from 20 reviews
    reviews: {
        averageRating: "4.4/5",
        items: [
            { // TODO: replace with real review text from Google Maps
                name: "Google Reviewer",
                role: "Verified Google Review",
                text: "Excellent service — very professional and reliable. Would highly recommend to anyone needing quality cleaning services in Uxbridge.",
                rating: 5,
            },
            { // TODO: replace with real review text from Google Maps
                name: "Google Reviewer",
                role: "Verified Google Review",
                text: "Very impressed with the standard of work. The team was punctual, thorough and friendly. Will definitely be using again.",
                rating: 5,
            },
            { // TODO: replace with real review text from Google Maps
                name: "Google Reviewer",
                role: "Verified Google Review",
                text: "Reliable, professional service. Our premises have never looked better. Great value for money.",
                rating: 5,
            },
        ],
    },

    // --- SERVICE AREAS ---
    // TODO: replace with their actual coverage areas from https://supremefacilities.co.uk/
    areas: {
        sectionTitle: "Areas We Cover",
        sectionSubtitle: "Providing professional cleaning services across Uxbridge and the surrounding areas.",
        locations: [
            "Uxbridge",
            "Uxbridge",
            "Hillingdon",
            "Hayes",
            "West Drayton",
            "Ickenham",
            "Harefield",
        ],
    },

    // --- FOOTER ---
    footer: {
        description: "Supreme Facilities Ltd — professional cleaning services you can trust. Fully insured, vetted staff, and a commitment to quality on every visit.", // TODO: personalize
        copyright: "© 2026 Supreme Facilities Ltd | All Rights Reserved.",
    },

    // --- TRUST BADGES ---
    trustBadges: ["Fully Insured", "Vetted Staff", "4.4★ Rated", "Free Quote"], // TODO: use their actual trust badges/USPs
};

export default config;
